[package]
name = "vpn_bot_tg"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15"

reqwest = {
    version = "0.13",
    default-features = false,
    features = ["json", "query", "rustls"]
}

serde = {
    version = "1",
    features = ["derive"]
}

teloxide = {
    version = "0.17",
    default-features = false,
    features = ["macros", "ctrlc_handler", "rustls", "tracing"]
}

thiserror = "2"

tokio = {
    version = "1",
    features = ["macros", "rt-multi-thread"]
}

tracing = "0.1"

tracing-subscriber = {
    version = "0.3",
    features = ["env-filter"]
}

chrono = "0.4"

sqlx = {
    version = "0.9",
    default-features = false,
    features = [
        "runtime-tokio",
        "postgres",
        "migrate",
        "macros",
        "chrono",
        "tls-rustls"
    ]
}